### ISSUE TITLE
404 on link

### ISSUE THREAD

**Issue by maboa** [pietrop/deepspeech-test#2]
https://github.com/mozilla/DeepSpeech/tree/master/examples/nodejs_wav linked to in the documentation results in a 404.

**Comment by pietrop** [comment]
ah, thanks, yes

>DeepSpeech examples were moved to a separate repository.
>
>New location: https://github.com/mozilla/DeepSpeech-examples

https://github.com/mozilla/DeepSpeech/tree/master/examples


will adjust the links

**Comment by pietrop** [comment]
ok, updated the links in the ADR PR https://github.com/pietrop/deepspeech-node-wrapper/pull/1
